#!/bin/bash

# This script will
# - check if arguments are supplied, and if they are not, will run jobs
#	on all directories, otherwise run on specified directories.
# - Runs sharcnet command on all specified moon_### directories.

beg=1
end=0

cd /work/esilber/moon

if [ $# -eq 0 ]; then
	echo "You haven't supplied any arguments, would you like to run all jobs? [y/n]"
	read ans
	# If yes is selected, then it will count all moon folders.
	if [ "$ans" == "y" ]; then
		end=`ls | grep "moon_###" | wc -l`
	else
		exit 2
	fi
elif [ $# -gt 2 ]; then
	echo "$0 requires 2 arguments"
elif [ $1 -ge $2 ]; then
	printf "Cannot _end on a _number before start!"
	exit 3
else
	beg=$1
	end=$2
fi

printf "Starting to run jobs from moon_"%03g" to moon_"%03g" directories\n" $beg $end

# Enter all the directories and run the command within those directories.
for m in $(seq -f "%03g" $beg $end); do
	cd /home/esilber/moon/moon_$m
	echo "Running sharcnet job in directory `pwd`"
	cp /work/esilber/iSALE_main_dam/bin/iSALE2D m$m
	sqsub -r 7d --mpp=2g -o run.log ./m$m
done
